AWSTemplateFormatVersion: '2010-09-09'
Description: VPC, Subnets publics/privés et Gateways.
Parameters:
  Env:
    Type: String
  VpcCidr:
    Type: String
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub mymusic-vpc-${Env}
Outputs:
  VpcId:
    Value: !Ref VPC
    Export:
      Name: !Sub ${Env}-VpcId
