AWSTemplateFormatVersion: '2010-09-09'
Description: Cluster ECS Fargate et définition des tâches.
Parameters:
  Env:
    Type: String
Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub mymusic-cluster-${Env}
